# BBM409 Fundamentals of  MACHINE LEARNİNG LAB.

# WEEK 1 - INTRODUCTION TO PYTHON

Instructor    : Aykut ERDEM

TA            : Burcak ASAL

Time          : Monday 15:00-17:00

Office hours  : Monday 14:00-15:00

Class webpage : https://web.cs.hacettepe.edu.tr/~aykut/classes/fall2019/bbm406/

Piazza        :https://piazza.com/hacettepe.edu.tr/fall2019/bbm406


## Grading

•Quizzes (20%) (Your lowest 2 quiz grades will be dropped.)

•Three assignments (done individually) which involve both theoretical and programming exercises (20%+30%+30%).

# Python


Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

Rich, built-in collection types:

• Lists

• Tuples

• Dictionaries (maps)

• Sets

In [2]:
# Writing first program

print("Hello World")

Hello World


In [3]:
# Basic data types

"""Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. 
These data types behave in ways that are familiar from other programming languages."""

#Numbers: Integers and floats work as you would expect from other languages:

x = 3
print(type(x))
print(x)
print(x + 1)
print(x - 1)
print(x * 2)
print(x ** 2)
x += 1
print(x)
x *= 2
print(x)
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

print("----------------------------------------")

# Booleans: Python implements all of the usual operators for Boolean logic, but uses 
#English words rather than symbols (&&, ||, etc.):

t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t != f)

print("----------------------------------------")

#Strings: Python has great support for strings:

hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world 
print(hw)
hw12 = '%s %s %d' % (hello, world, 12) 
print(hw12)

print("----------------------------------------")

#String objects have a bunch of useful methods; for example:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"




<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25
----------------------------------------
<class 'bool'>
False
True
False
True
----------------------------------------
hello
5
hello world
hello world 12
----------------------------------------
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [15]:
# Increment and Decrement Operators in Python


# A Sample Python program to show loop (unlike many # other languages, it doesn't use ++) 
for i in range(0, 5): 
   print(i) 


0
1
2
3
4


In [4]:
# Variables, Expressions, Conditions and Functions

# Variables
"""Variables need not be declared first in python. They can be used directly. 
Variables in python are case sensitive as most of the other programming languages."""

a = 3
A = 4
print(a) 
print(A) 
print("----------------------------------------")


# Expressions
"""Arithmetic operations in python can be performed by using arithmetic operators and some of the in-built functions."""

a = 2
b = 3
c = a + b 
print(c) 
d = a * b 
print(d) 
print("----------------------------------------")

# Conditions
"""Conditional output in python can be obtained by using if-else and elif (else if) statements."""

a = 3
b = 9
if b % a == 0 : 
    print("b is divisible by a")
elif b + 1 == 10: 
    print("Increment in b produces 10")
else: 
    print("You are in else statement")
print("----------------------------------------")
    
# Functions
"""A function in python is declared by the keyword ‘def’ before the name of the function. 
The return type of the function need not be specified explicitly in python. 
The function can be invoked by writing the function name followed by the parameter list in the brackets."""


# Function for checking the divisibility 
# Notice the indentation after function declaration 
# and if and else statements 
def checkDivisibility(a, b = 5): 
    if a % b == 0 : 
        print("a is divisible by b")
    else: 
        print("a is not divisible by b")
#Driver program to test the above function 
checkDivisibility(4) 
print("----------------------------------------")


3
4
----------------------------------------
5
6
----------------------------------------
b is divisible by a
----------------------------------------
a is not divisible by b
----------------------------------------


In [17]:
# Strings, Lists, Tuples, Iterations

# Strings
"""A string is a sequence of characters. It can be declared in python by using double quotes. 
Strings are immutable, i.e., they cannot be changed."""
# Assigning string to a variable 
a = "This is a string"
print(a) 
print("----------------------------------------")


#Lists
"""Lists are one of the most powerful tools in python. They are just like the arrays declared in other languages. 
But the most powerful thing is that list need not be always homogenous. 
A single list can contain strings, integers, as well as objects. 
Lists can also be used for implementing stacks and queues. Lists are mutable, i.e., they can be altered once declared."""

# Declaring a list 
L = [1, "a" , "string" , 1+2] 
print(L) 
L.append(6) 
print(L)
L.pop() # Remove and return the last element of the list
print(L)
print(L[1])

print(xs[-1])     # Negative indices count from the end of the list; prints "2"

#Slicing: In addition to accessing list elements one at a time, 
#Python provides concise syntax to access sublists; this is known as slicing:

nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

print("----------------------------------------")


# Tuples
"""A tuple is a sequence of immutable Python objects. 
Tuples are just like lists with the exception that tuples cannot be changed once declared. 
Tuples are usually faster than lists."""

tup = (1, "a", "string", 1+2) 
print(tup )
print(tup[1]) 
print("----------------------------------------")


# Iterations
"""Iterations or looping can be performed in python by ‘for’ and ‘while’ loops. 
Apart from iterating upon a particular condition, we can also iterate on strings, lists, and tuples."""

# Example1: Iteration by while loop for a condition
i = 1
while (i < 10): 
    i += 1
    print(i) 
print("----------------------------------------")


# Example 2: Iteration by for loop on string
s = "Hello World"
for i in s : 
    print(i) 
print("----------------------------------------")


# Example 3: Iteration by for loop on list
L = [1, 4, 5, 7, 8, 9] 
for  i in L: 
    print(i), 
print("----------------------------------------")
    
#Example 4 : Iteration by for loop for range
for  i in range(0, 10): 
    print(i) 
print("----------------------------------------")

# List comprehensions

"""When programming, frequently we want to transform one type of data into another. 
As a simple example, consider the following code that computes square numbers:"""

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares) 
print("----------------------------------------")
# You can make this code simpler using a list comprehension:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares) 
print("----------------------------------------")

#List comprehensions can also contain conditions:

nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)
print("----------------------------------------")

This is a string
----------------------------------------
[1, 'a', 'string', 3]
[1, 'a', 'string', 3, 6]
[1, 'a', 'string', 3]
a


NameError: name 'xs' is not defined

In [ ]:
# Dictionaris

"""A dictionary stores (key, value) pairs, similar to a Map in Java or an object in Javascript."""

d = {'cat': 'cute', 'dog': 'furry'}
print(d['cat'])
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"
print("----------------------------------------")


#If you want access to keys and their corresponding values, use the items method:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
print("----------------------------------------")

# Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. 
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)
print("----------------------------------------")

In [ ]:
# Sets

"""A set is an unordered collection of distinct elements."""
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"


In [ ]:
# Classes

"""The syntax for defining classes in Python is straightforward:"""

class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"


# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [18]:
"""We can initialize numpy arrays from nested Python lists, and access elements using square brackets:"""

import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"
print("----------------------------------------")

#Numpy also provides many functions to create arrays:
import numpy as np

a = np.zeros((2,2))
print(a) 
print("----------------------------------------")

b = np.ones((1,2)) 
print(b)
print("----------------------------------------")

c = np.full((2,2), 7)
print(c) 
print("----------------------------------------")

d = np.eye(2)
print(d) 
print("----------------------------------------")

e = np.random.random((2,2))
print(e)
print("----------------------------------------")

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
----------------------------------------
[[0. 0.]
 [0. 0.]]
----------------------------------------
[[1. 1.]]
----------------------------------------
[[7 7]
 [7 7]]
----------------------------------------
[[1. 0.]
 [0. 1.]]
----------------------------------------
[[0.74114014 0.75512823]
 [0.11460861 0.99426372]]
----------------------------------------


# Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [19]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))
print("----------------------------------------")

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))
print("----------------------------------------")

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))
print("----------------------------------------")

# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))
print("----------------------------------------")

# Elementwise square root; produces the array
print(np.sqrt(x))
print("----------------------------------------")

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors;
print(v.dot(w))
print(np.dot(v, w))
print("----------------------------------------")

# Matrix / vector product; both produce the rank 1 array
print(x.dot(v))
print(np.dot(x, v))
print("----------------------------------------")

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))
print("----------------------------------------")

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
----------------------------------------
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
----------------------------------------
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
----------------------------------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
----------------------------------------
[[1.         1.41421356]
 [1.73205081 2.        ]]
----------------------------------------
219
219
----------------------------------------
[29 67]
[29 67]
----------------------------------------
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
----------------------------------------


Note : Python examples are taken from https://www.geeksforgeeks.org/python-language-introduction/ .
       Numpy examples are taken from http://cs231n.github.io/python-numpy-tutorial/  